package ir.proxyyab.app

object DefaultSources {
    val urls: List<String> = """
https://t.me/V2rayNgBmx
https://t.me/mitivpn
https://t.me/proxyplus
https://t.me/miticonfig
https://t.me/proxyrp
https://t.me/PinkProxy
https://t.me/Myporoxy
https://t.me/v2ray_free_conf
https://t.me/FreakConfig
https://t.me/ProxyMTProto
https://t.me/AR14N24B
https://t.me/vpnfail_v2ray
https://t.me/configraygan
https://t.me/V2rayng_Fast
https://t.me/V2rayNGn
https://t.me/DirectVPN
https://t.me/NetAccount
https://t.me/Outline_Vpn
https://t.me/ShadowSocks_s
https://t.me/internet4iran
https://t.me/UnlimitedDev
https://t.me/v2rayngvpn
https://t.me/hassan_saboorii
https://t.me/server01012
https://t.me/kiava
https://t.me/VpnProSec
https://t.me/hashmakvpn
https://t.me/iran_ray
https://t.me/ServerNett
https://t.me/DarkVPNpro
https://t.me/shopingv2ray
https://t.me/free4allVPN
https://t.me/ProxyFn
https://t.me/oneclickvpnkeys
https://t.me/vpn_xw
https://t.me/azadi_az_inja_migzare
https://t.me/LegenderY_Servers
https://t.me/vmessorg
https://t.me/vpn_ioss
https://t.me/FalconPolV2rayNG
https://t.me/v2rayvmess
https://t.me/ShadowProxy66
https://t.me/Helix_Servers
https://t.me/VlessConfig
https://t.me/X_Her0
https://t.me/INIT1984
https://t.me/Pinkpotatocloud
https://t.me/Qv2raychannel
https://t.me/xrayproxy
https://t.me/PrivateVPNs
https://t.me/v2ray_outlineir
https://t.me/daorzadannet
https://t.me/prrofile_purple
https://t.me/WomanLifeFreedomVPN
https://t.me/v2rayNG_Matsuri
https://t.me/v2freevpn
https://t.me/Jeyksatan
https://t.me/v2rayNGNeT
https://t.me/ipV2Ray
https://t.me/PAINB0Y
https://t.me/NIM_VPN_ir
https://t.me/Napsternetvirani
https://t.me/EXOGAMERS
https://t.me/CloudCityy
https://t.me/xrayzxn
https://t.me/Proxy_PJ
https://t.me/LoRd_uL4mo
https://t.me/proxyymeliii
https://t.me/MsV2ray
https://t.me/free_v2rayy
https://t.me/v2ray1_ng
https://t.me/vless_vmess
https://t.me/MTConfig
https://t.me/lagvpn13
https://t.me/v2rayNG_VPNN
https://t.me/vmess_vless_v2rayng
https://t.me/FreeIranT
https://t.me/Cov2ray
https://t.me/V2RayTz
https://t.me/VmessProtocol
https://t.me/MehradLearn
https://t.me/SafeNet_Server
https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
https://raw.githubusercontent.com/MrAbolfazlNorouzi/iran-configs/main/configs/working-configs.txt
https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/main/V2Ray-Config-By-EbraSha-All-Type.txt
https://github.com/Mohammadgb0078/IRV2ray
https://github.com/gfpcom/free-proxy-list
https://github.com/licheng527/Free-servers
    """.trimIndent().lines().map { it.trim() }.filter { it.isNotBlank() }.distinct()
}
